services:
  postgres:
    image: postgres:16
    container_name: aml-postgres
    environment:
      POSTGRES_DB: aml_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: aml-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/aml_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
